/**
 * 60갑자별 강점·주의할 점·추천 직업 (일주에 맞게 결과 페이지 노출)
 */
export type PillarCareerEntry = {
  strengths: string[]
  challenges: string[]
  career: { best: string[]; avoid: string[] }
}

export const PILLAR_STRENGTHS_CHALLENGES_CAREER: Record<string, PillarCareerEntry> = {
  "甲子": { strengths: ["잠재력", "통찰력", "적응력"], challenges: ["성급함", "고립"], career: { best: ["연구", "전략", "컨설팅"], avoid: ["단순 반복 업무"] } },
  "甲寅": { strengths: ["리더십", "개척정신", "결단력"], challenges: ["고집", "성급한 판단"], career: { best: ["경영", "정치", "사업"], avoid: ["수동적 역할"] } },
  "甲辰": { strengths: ["안정감", "비전", "균형"], challenges: ["우유부단", "과한 욕심"], career: { best: ["기획", "PM", "부동산"], avoid: ["불안정한 환경"] } },
  "甲午": { strengths: ["열정", "성취욕", "카리스마"], challenges: ["번아웃", "독단"], career: { best: ["마케팅", "영업", "엔터테인먼트"], avoid: ["암묵적 업무"] } },
  "甲申": { strengths: ["세련됨", "예술성", "완성도"], challenges: ["완벽주의", "비판적 성향"], career: { best: ["디자인", "예술", "미디어"], avoid: ["대량 생산 위주"] } },
  "甲戌": { strengths: ["충성심", "보호 본능", "신뢰"], challenges: ["경직됨", "변화 회피"], career: { best: ["공직", "법률", "보안"], avoid: ["빈번한 전환"] } },
  "乙丑": { strengths: ["인내심", "양육", "꾸준함"], challenges: ["소극적", "우유부단"], career: { best: ["교육", "농업", "요리"], avoid: ["고압적 환경"] } },
  "乙卯": { strengths: ["부드러움", "조화", "협상력"], challenges: ["우유부단", "경계 부재"], career: { best: ["HR", "외교", "상담"], avoid: ["갈등 심한 직군"] } },
  "乙巳": { strengths: ["열정", "끈기", "표현력"], challenges: ["질투", "변덕"], career: { best: ["영업", "연예", "PR"], avoid: ["단조로운 업무"] } },
  "乙未": { strengths: ["배려", "치유", "평화"], challenges: ["희생 과다", "자기 소홀"], career: { best: ["의료", "복지", "상담"], avoid: ["경쟁 중심"] } },
  "乙酉": { strengths: ["세밀함", "미적 감각", "완벽 추구"], challenges: ["예민함", "자기 비난"], career: { best: ["금속·보석", "공예", "품질 관리"], avoid: ["대충 처리"] } },
  "乙亥": { strengths: ["직관", "공감", "상상력"], challenges: ["현실 도피", "감정 기복"], career: { best: ["예술", "심리", "영상"], avoid: ["숫자·규칙만 있는 업무"] } },
  "丙子": { strengths: ["따뜻함", "희망", "포용"], challenges: ["수동적", "의존"], career: { best: ["교육", "복지", "서비스"], avoid: ["냉정한 경쟁"] } },
  "丙寅": { strengths: ["선도력", "열정", "동력"], challenges: ["성급함", "무리한 도전"], career: { best: ["스타트업", "영업", "광고"], avoid: ["보수적 조직"] } },
  "丙辰": { strengths: ["안정적 리더십", "균형", "지속력"], challenges: ["과한 책임감", "번아웃"], career: { best: ["경영", "공공", "인프라"], avoid: ["불확실한 구조"] } },
  "丙午": { strengths: ["당당함", "정직", "파워"], challenges: ["독단", "과한 자존심"], career: { best: ["CEO", "정치", "법조"], avoid: ["숨는 역할"] } },
  "丙申": { strengths: ["세련된 비전", "예술성", "분석력"], challenges: ["냉정해 보임", "완벽주의"], career: { best: ["기획", "미디어", "컨설팅"], avoid: ["단순 노동"] } },
  "丙戌": { strengths: ["따뜻한 보호", "충성", "양육"], challenges: ["집착", "경계 부재"], career: { best: ["교육", "의료", "공직"], avoid: ["이기적 환경"] } },
  "丁丑": { strengths: ["부드러운 이끌림", "예술성", "배려"], challenges: ["소극적", "우유부단"], career: { best: ["교육", "상담", "예술"], avoid: ["공격적 영업"] } },
  "丁卯": { strengths: ["창의성", "조화", "혁신"], challenges: ["산만함", "결단 부족"], career: { best: ["디자인", "기획", "창작"], avoid: ["경직된 규칙"] } },
  "丁巳": { strengths: ["빼어난 지성", "통찰", "신비로움"], challenges: ["과한 내향", "소통 부족"], career: { best: ["연구", "IT", "전략"], avoid: ["단순 대인 업무"] } },
  "丁未": { strengths: ["치유", "양육", "평화"], challenges: ["희생 과다", "자기 주장 약함"], career: { best: ["의료", "복지", "요리"], avoid: ["고압적 환경"] } },
  "丁酉": { strengths: ["우아한 완벽주의", "세밀함", "품격"], challenges: ["예민함", "비판적"], career: { best: ["금세공", "편집", "품질"], avoid: ["대충하는 문화"] } },
  "丁亥": { strengths: ["상상력", "감수성", "로맨스"], challenges: ["현실 도피", "우유부단"], career: { best: ["예술", "글쓰기", "영상"], avoid: ["숫자·규칙 위주"] } },
  "戊子": { strengths: ["유연함", "사유", "균형"], challenges: ["우유부단", "기준 흔들림"], career: { best: ["컨설팅", "연구", "전략"], avoid: ["경직된 구조"] } },
  "戊寅": { strengths: ["위엄", "책임감", "리더십"], challenges: ["고집", "완고함"], career: { best: ["경영", "공직", "건설"], avoid: ["사수 없는 역할"] } },
  "戊辰": { strengths: ["풍요", "현실감", "전략"], challenges: ["욕심", "완고함"], career: { best: ["금융", "부동산", "사업"], avoid: ["불안정 수입"] } },
  "戊午": { strengths: ["밝은 리더십", "에너지", "결단"], challenges: ["독단", "성급함"], career: { best: ["경영", "영업", "정치"], avoid: ["숨는 포지션"] } },
  "戊申": { strengths: ["견고함", "전략", "원칙"], challenges: ["경직", "융통성 부족"], career: { best: ["엔지니어링", "법률", "전략"], avoid: ["감정 중심 업무"] } },
  "戊戌": { strengths: ["충성심", "책임감", "신뢰"], challenges: ["융통성", "변화 수용"], career: { best: ["공직", "법률", "보안"], avoid: ["빈번한 전환"] } },
  "己丑": { strengths: ["인내", "양육", "배려"], challenges: ["소극적", "우유부단"], career: { best: ["교육", "농업", "요리"], avoid: ["고압적 환경"] } },
  "己卯": { strengths: ["조화", "부드러움", "미감"], challenges: ["우유부단", "경계 부재"], career: { best: ["디자인", "상담", "정원"], avoid: ["갈등 심한 직군"] } },
  "己巳": { strengths: ["세련된 창작", "열정", "꼼꼼함"], challenges: ["완벽주의", "예민함"], career: { best: ["디자인", "공예", "기획"], avoid: ["대충하는 문화"] } },
  "己未": { strengths: ["따뜻한 양육", "풍요", "평화"], challenges: ["희생 과다", "자기 주장 약함"], career: { best: ["요리", "복지", "농업"], avoid: ["냉정한 경쟁"] } },
  "己酉": { strengths: ["소중함", "인내", "꼼꼼함"], challenges: ["숨김", "자기 과소평가"], career: { best: ["보석", "품질", "연구"], avoid: ["과시하는 역할"] } },
  "己亥": { strengths: ["직관", "배려", "창의"], challenges: ["감정 기복", "현실 도피"], career: { best: ["상담", "예술", "요리"], avoid: ["숫자만 보는 업무"] } },
  "庚子": { strengths: ["날카로운 분석", "명쾌함", "정의감"], challenges: ["냉정해 보임", "경직됨"], career: { best: ["법률", "의료", "연구"], avoid: ["모호한 기준"] } },
  "庚寅": { strengths: ["용기", "강인함", "선도"], challenges: ["성급함", "공격적"], career: { best: ["군·경", "스포츠", "엔지니어링"], avoid: ["수동적 역할"] } },
  "庚辰": { strengths: ["견고함", "원칙", "기반"], challenges: ["융통성 부족", "완고함"], career: { best: ["건설", "금융", "공직"], avoid: ["불안정 구조"] } },
  "庚午": { strengths: ["정제된 힘", "열정", "완벽 추구"], challenges: ["독단", "과한 기준"], career: { best: ["군인", "스포츠", "공학"], avoid: ["애매한 역할"] } },
  "庚申": { strengths: ["완벽", "마스터리", "집중"], challenges: ["과한 완벽주의", "냉정함"], career: { best: ["기술", "외과", "공예"], avoid: ["대충 처리"] } },
  "庚戌": { strengths: ["충성", "보호", "원칙"], challenges: ["경직", "변화 회피"], career: { best: ["법률", "보안", "공직"], avoid: ["유연성만 요구"] } },
  "辛丑": { strengths: ["소중함", "인내", "꼼꼼함"], challenges: ["숨김", "소극적"], career: { best: ["보석", "금융", "품질"], avoid: ["과시 위주"] } },
  "辛卯": { strengths: ["우아함", "예술성", "섬세함"], challenges: ["예민함", "완벽주의"], career: { best: ["금세공", "디자인", "편집"], avoid: ["거친 환경"] } },
  "辛巳": { strengths: ["정제된 완벽", "열정", "고급스러움"], challenges: ["냉정해 보임", "과한 기준"], career: { best: ["귀금속", "패션", "럭셔리"], avoid: ["대량 생산"] } },
  "辛未": { strengths: ["부드러운 기술", "배려", "완성도"], challenges: ["우유부단", "자기 주장 약함"], career: { best: ["은세공", "요리", "상담"], avoid: ["공격적 영업"] } },
  "辛酉": { strengths: ["빼어난 재능", "정제됨", "완벽"], challenges: ["자기 비난", "예민함"], career: { best: ["예술", "IT", "연구"], avoid: ["대충하는 문화"] } },
  "辛亥": { strengths: ["숨은 보석", "직관", "섬세함"], challenges: ["소극적", "현실 도피"], career: { best: ["연구", "예술", "상담"], avoid: ["과시하는 역할"] } },
  "壬子": { strengths: ["넓은 포용", "지혜", "직관"], challenges: ["산만함", "깊이 부족"], career: { best: ["국제", "연구", "영상"], avoid: ["좁은 범위"] } },
  "壬寅": { strengths: ["흐르는 힘", "창의", "역동"], challenges: ["산만함", "집중 부족"], career: { best: ["사업", "영업", "미디어"], avoid: ["정체된 환경"] } },
  "壬辰": { strengths: ["전략", "현실감", "균형"], challenges: ["과한 계산", "냉정해 보임"], career: { best: ["금융", "전략", "PM"], avoid: ["감정만으로 결정"] } },
  "壬午": { strengths: ["변화 이끔", "열정", "혁신"], challenges: ["불안정", "집중 부족"], career: { best: ["스타트업", "마케팅", "미디어"], avoid: ["고정된 루틴"] } },
  "壬申": { strengths: ["맑은 원천", "정의", "정직"], challenges: ["경직됨", "융통성 부족"], career: { best: ["법률", "의료", "연구"], avoid: ["모호한 기준"] } },
  "壬戌": { strengths: ["믿음직함", "지혜", "베풂"], challenges: ["과한 책임", "번아웃"], career: { best: ["교육", "공직", "복지"], avoid: ["이기적 환경"] } },
  "癸丑": { strengths: ["부드러운 양육", "배려", "인내"], challenges: ["소극적", "우유부단"], career: { best: ["교육", "요리", "복지"], avoid: ["고압적 환경"] } },
  "癸卯": { strengths: ["부드러운 촉매", "창의", "조화"], challenges: ["우유부단", "경계 부재"], career: { best: ["상담", "디자인", "교육"], avoid: ["갈등 심한 직군"] } },
  "癸巳": { strengths: ["신비로운 직관", "예술성", "은은함"], challenges: ["현실 도피", "소통 부족"], career: { best: ["연구", "예술", "상담"], avoid: ["숫자만 보는 업무"] } },
  "癸未": { strengths: ["조용한 치유", "배려", "평화"], challenges: ["희생 과다", "자기 소홀"], career: { best: ["의료", "복지", "요리"], avoid: ["경쟁 중심"] } },
  "癸酉": { strengths: ["섬세한 완벽", "아름다움", "정제됨"], challenges: ["예민함", "자기 비난"], career: { best: ["예술", "편집", "품질"], avoid: ["대충하는 문화"] } },
  "癸亥": { strengths: ["깊은 통찰", "신비", "상상"], challenges: ["현실 도피", "과한 내향"], career: { best: ["철학", "영적 지도", "예술"], avoid: ["표면적 업무"] } }
}
